### ISSUE TITLE
Required properties are not shown as required

### ISSUE THREAD

**Issue by mnonnenmacher** [SMILEY4/schema-kenerator#16]
I am testing version 1.2.2 and noticed that now a lot of properties are not marked as required anymore compared to version 1.1.1 (this could maybe be related to the fix for #14).

For example, for this data class the `name` should be required and the `description` should not be:

```kotlin
data class CreateProduct(
    val name: String,
    val description: String? = null
)
```

Version 1.1.1 sets `required` correctly:

```json
      "CreateProduct" : {
        "title" : "CreateProduct",
        "required" : [ "name" ],
        "type" : "object",
        "properties" : {
          "description" : {
            "title" : "String",
            "type" : "string"
          },
          "name" : {
            "title" : "String",
            "type" : "string"
          }
        }
      }
```

With 1.2.2 required is empty:

```json
      "CreateProduct" : {
        "title" : "CreateProduct",
        "type" : "object",
        "properties" : {
          "description" : {
            "title" : "String",
            "type" : "string"
          },
          "name" : {
            "title" : "String",
            "type" : "string"
          }
        }
      }
```

In both cases I am using:

```kotlin
.generateSwaggerSchema {
    optionalHandling = OptionalHandling.NON_REQUIRED
}
```

And maybe also related, the type for the `description` should actually be `"type": ["string", "null"]` as it is a nullable property.

**Comment by SMILEY4** [comment]
Hi,   thanks for the report.
I fixed it with version 1.2.3 - the whole type-parsing and nullability thing got a bit more complicated than i first thought :)  so i hope it works now.
I'm not 100% sure about `"type": ["string", "null"]`. As far as i understand "https://swagger.io/docs/specification/data-models/data-types/#null" there is no "null" but a property "nullable". :thinking:  I'll have another look at that again.

**Comment by mnonnenmacher** [comment]
> Hi, thanks for the report. I fixed it with version 1.2.3 - the whole type-parsing and nullability thing got a bit more complicated than i first thought :) so i hope it works now.

Thank you, I will give it a try.

> I'm not 100% sure about `"type": ["string", "null"]`.  As far as i understand "https://swagger.io/docs/specification/data-models/data-types/#null" there is no "null" but a property "nullable". 🤔 I'll have another look at that again.

To my understanding this is a limitation of version 3.0 of the spec. It says:

> `null` is not supported as a type (see [nullable](https://swagger.io/specification/v3/#schema-nullable) for an alternative solution).

https://swagger.io/specification/v3/#data-types

That sentence is gone in version 3.1:

https://swagger.io/specification/#data-types

**Comment by mnonnenmacher** [comment]
I just noticed, at your link it also says:

> OpenAPI 3.0 does not have an explicit null type

**Comment by mnonnenmacher** [comment]
Something went wrong with the 1.2.3 release, the artifacts on Maven Central were released with version 1.3.0.

I tested that version, but for the `CreateProduct` class the `name` property is still not marked as required.

This is the configuration I am using:

```kotlin
schemas {
    generator = { type ->
        type
            .collectSubTypes()
            .processReflection {
                redirect<Instant, String>()
                redirect<Instant?, String?>()
                redirect<OptionalValue<String>, String>()
                redirect<OptionalValue<String?>, String?>()
                redirect<OptionalValue<RepositoryType>, RepositoryType>()
                redirect<OptionalValue<Set<CredentialsType>>, Set<CredentialsType>>()
            }
            .connectSubTypes()
            .handleNameAnnotation()
            .generateSwaggerSchema {
                optionalHandling = OptionalHandling.NON_REQUIRED
            }
            .handleCoreAnnotations()
            .withTitle(TitleType.OPENAPI_SIMPLE)
            .compileReferencingRoot(RefType.OPENAPI_SIMPLE)
    }
}
```

**Comment by rmcmk** [comment]
Experiencing the same here. Required property flag mismatch and the versioning mismatch on maven.

**Comment by SMILEY4** [comment]
Dang, thanks for noticing! I think i screwed up when publishing the version.
I'll still release 1.2.3 as it should have been and try to get a new correct 1.3.1 out as soon as possible since I'm not 100% sure in which state it (1.3.0) is in (i think its just missing the 1.2.3. fix).

**Comment by mnonnenmacher** [comment]
I can confirm that the issue with the missing required properties is fixed in the new 1.2.3 release.
